AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Default: develop
    Description: Environment name (develop, prod, etc.)
Resources:
  SensorDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "SensorData-${Environment}"
      AttributeDefinitions:
        - AttributeName: sensorId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: sensorId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  UserGreenhousesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "UserGreenhouses-${Environment}"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: greenhouseId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: greenhouseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SensorInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "SensorInfo-${Environment}"
      AttributeDefinitions:
        - AttributeName: sensorId
          AttributeType: S
      KeySchema:
        - AttributeName: sensorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST